msfs_mode = 1

parkings = {
    GATE : {
        None : (),
        4 : (CustomizedName("Apron 1 Gate|Spot 4A [ANA/ANA WINGS]"), ),
        5 : (CustomizedName("Apron 1 Gate|Spot 5 [ANA/ANA WINGS]"), ),
        6 : (CustomizedName("Apron 1 Gate|Spot 6 [ANA]"), ),
        7 : (CustomizedName("Apron 1 Gate|Spot 7 [ANA]"), ),
        8 : (CustomizedName("Apron 2 Gate|Spot 8 [ANA]"), ),
        9 : (CustomizedName("Apron 2 Gate|Spot 9 [ANA]"), ),
        11 : (CustomizedName("Apron 2 Gate|Spot 11 [ANA]"), ),
        12 : (CustomizedName("Apron 3 Gate|Spot 12 [ANA]"), ),
        13 : (CustomizedName("Apron 3 Gate|Spot 13 [ANA]"), ),
        14 : (CustomizedName("Apron 3 Gate|Spot 14 [JAL/J-AIR]"), ),
        15 : (CustomizedName("Apron 3 Gate|Spot 15 [JAL/J-AIR]"), ),
        16 : (CustomizedName("Apron 4 Gate|Spot 16 [JAL/J-AIR]"), ),
        17 : (CustomizedName("Apron 4 Gate|Spot 17 [JAL/J-AIR]"), ),
        19 : (CustomizedName("Apron 4 Gate|Spot 19 [JAL/J-AIR]"), ),
        20 : (CustomizedName("Apron 5 Gate|Spot 20 [JAL/J-AIR]"), ),
        21 : (CustomizedName("Apron 5 Gate|Spot 21 [JAL/J-AIR]"), ),
        22 : (CustomizedName("Apron 5 Gate|Spot 22 [JAL/J-AIR]"), ),
        23 : (CustomizedName("Apron 5 Gate|Spot 23 [J-AIR/AMX/JAC]"), ),
    },
    PARKING : {
        None : (),
        0 : (CustomizedName("Apron 1 Stand|Spot #§"), ),
        1 : (CustomizedName("Apron 1 Stand|Spot #§"), ),
        2 : (CustomizedName("Apron 1 Stand|Spot #§ [ANA WINGS/IBEX]"), ),
        3 : (CustomizedName("Apron 1 Stand|Spot #§ [ANA WINGS/IBEX]"), ),
        4 : (CustomizedName("Apron 1 Stand|Spot #§ [ANA WINGS/IBEX]"), ),
        18 : (CustomizedName("Apron 4 Gate|Spot 18 [JAL/J-AIR]"), ),
        24 : (CustomizedName("Apron 5 Stand|Spot 24 [J-AIR/JAC]"), ),
        25 : (CustomizedName("Apron 5 Stand|Spot 25 [J-AIR/JAC]"), ),
        26 : (CustomizedName("Apron 5 Stand|Spot 26 [J-AIR/JAC]"), ),
        27 : (CustomizedName("Apron 5 Stand|Spot 27 [J-AIR/JAC]"), ),
        41 : (CustomizedName("Apron 5 Stand|Spot 41 [J-AIR]"), ),
        42 : (CustomizedName("Apron 5 Stand|Spot 42 [J-AIR]"), ),
        43 : (CustomizedName("Apron 5 Stand|Spot 43 [BROKEN]"), ),
        44 : (CustomizedName("Apron 5 Stand|Spot 44 [BROKEN]"), ),
        45 : (CustomizedName("Apron 6 Stand|Spot #§ [J-AIR/JAC]"), ),
        46 : (CustomizedName("Apron 6 Stand|Spot 46 [J-AIR/JAC]"), ),
        47 : (CustomizedName("Apron 6 Stand|Spot 47 [J-AIR/JAC]"), ),
        48 : (CustomizedName("Apron 6 Stand|Spot 48 [J-AIR/JAC]"), ),
        51 : (CustomizedName("Apron 6 Stand|Spot #§"), ),
        52 : (CustomizedName("Apron 6 Stand|Spot #§"), ),
        53 : (CustomizedName("Apron 6 Stand|Spot #§"), ),
        70 : (CustomizedName("Apron 7 Stand|Spot #§"), ),
        71 : (CustomizedName("Apron 7 Stand|Spot #§"), ),
        72 : (CustomizedName("Apron 7 Stand|Spot #§"), ),
        73 : (CustomizedName("Apron 7 Stand|Spot #§"), ),
        74 : (CustomizedName("Apron 7 Stand|Spot #§"), ),
        75 : (CustomizedName("Apron 7 Stand|Spot #§"), ),
        76 : (CustomizedName("Apron 7 Stand|Spot #§"), ),
        77 : (CustomizedName("Apron 7 Stand|Spot #§"), ),
        80 : (CustomizedName("Apron 8 Stand|Spot #§"), ),
        81 : (CustomizedName("Apron 8 Stand|Spot #§"), ),
        82 : (CustomizedName("Apron 8 Stand|Spot #§"), ),
        83 : (CustomizedName("Apron 8 Stand|Spot #§"), ),
        84 : (CustomizedName("Apron 8 Stand|Spot #§"), ),
    },
    0 : {
        None : (),
        10 : (CustomizedName("Apron 2 Gate|Spot 10 [ANA]"), ),
    }
}